# -*- coding: utf-8 -*-
"""clean_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EcvAHJXpJlf6WdY2Ib0cNTmOozmI8nPs
"""

import pandas as pd

# Load Delhi dataset
delhi_df = pd.read_csv("city_hour.csv")

# Filter for Delhi only
delhi_df = delhi_df[delhi_df['City'] == 'Delhi']

# Parse datetime and filter needed columns
delhi_df['Datetime'] = pd.to_datetime(delhi_df['Datetime'], errors='coerce')

# Keep only necessary columns
delhi_df = delhi_df[['Datetime', 'PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'CO', 'SO2', 'O3']]

# Remove missing values
delhi_df = delhi_df.dropna()

# Load Madrid dataset
madrid_df = pd.read_csv("MadridPolution2001-2022.csv")

# Convert 'Time' to datetime and filter by year
madrid_df['Time'] = pd.to_datetime(madrid_df['Time'], errors='coerce')
madrid_df = madrid_df[(madrid_df['Time'].dt.year >= 2015) & (madrid_df['Time'].dt.year <= 2020)]

# Rename Madrid columns to match Delhi
rename_map = {
    'Time': 'Datetime',
    'PM25': 'PM2.5',
    'PM10': 'PM10',
    'NO': 'NO',
    'NO2': 'NO2',
    'NOx': 'NOx',
    'CO': 'CO',
    'SO2': 'SO2',
    'O3': 'O3'
}
madrid_df = madrid_df.rename(columns=rename_map)

# Keep only matching columns
madrid_df = madrid_df[list(rename_map.values())]

# Remove missing values
madrid_df = madrid_df.dropna()

# Reorder Delhi columns to match Madrid
delhi_df = delhi_df[madrid_df.columns]

# Define air quality category function
def classify_pm25(pm25):
    if pm25 <= 12:
        return 'Good'
    elif pm25 <= 35:
        return 'Moderate'
    elif pm25 <= 55:
        return 'Unhealthy'
    elif pm25 <= 150:
        return 'Poor'
    elif pm25 <= 250:
        return 'Very Poor'
    else:
        return 'Hazardous'

# Apply to both datasets
delhi_df['AQI_Category'] = delhi_df['PM2.5'].apply(classify_pm25)
madrid_df['AQI_Category'] = madrid_df['PM2.5'].apply(classify_pm25)

# Remove timezone from Madrid datetime
madrid_df['Datetime'] = madrid_df['Datetime'].dt.tz_localize(None)

# Show samples
print("Delhi Data Sample:")
print(delhi_df.head())

print("\nMadrid Data Sample:")
print(madrid_df.head())

# Save cleaned datasets to Excel files
delhi_df.to_excel("Delhi.xlsx", index=False)
madrid_df.to_excel("Madrid.xlsx", index=False)